Controllers/BlogController.cs
using System.Threading.Tasks;
using App.Data.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SimoshStore;

namespace MyApp.Namespace
{
    public class BlogController : Controller
    {
        ITagService _tagService;
        IDataRepository _Repository;
        IBlogService _blogService;
        IBlogCategoryService _blogCategoryService;
        ICategoryService _categoryService;
        IProductService _productService;
        IUserService _userService;
        public BlogController(IUserService userService, ITagService tagService, ICategoryService categoryService, IProductService productService, IDataRepository dataRepository, IBlogService blogService, IBlogCategoryService blogCategoryService)
        {
            _Repository = dataRepository;
            _blogCategoryService = blogCategoryService;
            _blogService = blogService;
            _productService = productService;
            _categoryService = categoryService;
            _tagService = tagService;
            _userService = userService;
        }
        public async Task<IActionResult> BlogPost(int id)
        {
            var randomBlog = await _blogService.GetRandomBlog();
            var blogEntity = await _blogService.GetBlogByIdAsync(id);
            if (blogEntity is null)
            {
                return RedirectToAction("UnderConstruction", "Error");
            }
            var blogEntities = await _blogService.GetAllBlogsAsync();
            var blogComments = await _blogService.GetComments(id);
            var relBlogTags = await _Repository.GetAll<RelBlogTagEntity>().ToListAsync();
            var user = await _Repository.GetByIdAsync<UserEntity>(blogEntity.UserId);
            List<BlogTagEntity> tags = new List<BlogTagEntity>();
            foreach (var relBlogTag in relBlogTags)
            {
                var tag = await _tagService.GetTagByIdAsync(relBlogTag.TagId);
                tags.Add(tag);
            }
            if (user is null)
            {
                user = new UserEntity();
            }
            return View(new BlogPostViewModel
            {
                randomBlog = randomBlog,
                blog = blogEntity,
                blogs = blogEntities,
                blogComments = blogComments,
                user = user,
                quote = QuoteHelper.GenerateQuote(),
                tags = tags

            });

        }
        public async Task<IActionResult> DeleteBlog(int id)
        {
            await _blogService.DeleteBlogAsync(id);
            return RedirectToAction("ListBlogs","Admin");
        }
        public async Task<IActionResult> BlogList()
        {
            var blogEntities = await _blogService.GetAllBlogsAsync();
            var blogCategoryEntities = await _blogCategoryService.GetAllCategoriesAsync();
            return View(new BlogListViewModel
            {
                blogCategoryEntities = blogCategoryEntities,
                blogEntities = blogEntities,

            });
        }
        public async Task<IActionResult> BlogListWithTag(BlogTagEntity blogTagEntity)
        {
            return RedirectToAction("UnderConstruction", "Error");
        }
        public async Task<IActionResult> RecentBlogs()
        {
            var blogEntities = await _blogService.GetRecentBlogs();
            return View(blogEntities);
        }
        public async Task<IActionResult> CreateBlog()
        {
            int userId = _userService.GetUserId();
            var user = await _userService.GetUserByIdAsync(userId);
            if (user is null)
            {
                return RedirectToAction("Login", "Account");
            }
            return View(new BlogDTO{
                userId = userId
            });
        }
        [HttpPost]
        public async Task<IActionResult> CreateBlog(BlogDTO blogDTO)
        {
            var blog = await _blogService.CreateBlogAsync(blogDTO);
            return RedirectToAction("BlogList");
        }
    }
}

Views/Shared/Components/BlogSection/default.cshtml
@using App.Data.Entities
@model List<BlogEntity>

@{
}
@foreach(var blog in Model)
					{
						<div class="swiper-slide">
						<div class="dz-card style-2 wow fadeInUp" data-wow-delay="0.2s">
							<div class="dz-media">
								<img src="https://picsum.photos/600/675" alt="">
								<div class="post-date">@blog.CreatedAt.ToString("dd MMM yyyy")</div>
							</div>
							<div class="dz-info">
								<h3 class="dz-title mb-0">
									<a href="@Url.Action("BlogPost","Blog",new{id = blog.Id})">@blog.Title</a>
								</h3>
								<ul class="blog-social">
									<li>
										<a class="share-btn" href="javascript:void(0);">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
												<path d="M7 17L17 7" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
												<path d="M7 7H17V17" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
											</svg>
										</a>								
										<ul class="sub-team-social">
											<li><a href="https://www.instagram.com/s4rgin" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
											<li><a href="https://www.instagram.com/s4rgin" target="_blank"><i class="fab fa-twitter"></i></a></li>
											<li><a href="https://www.instagram.com/s4rgin" target="_blank"><i class="fab fa-instagram"></i></a></li>
											<li><a href="https://www.instagram.com/s4rgin" target="_blank"><i class="fa-brands fa-linkedin-in"></i></a></li>
										</ul>
									</li>
								</ul>
							</div>
						</div>
					</div>
					}
					@foreach(var blog in Model)
					{
						<div class="swiper-slide">
						<div class="dz-card style-2 wow fadeInUp" data-wow-delay="0.4s">
							<div class="dz-media">
								<img src="https://picsum.photos/480/480" alt="">
								<div class="post-date">@blog.CreatedAt.ToString("dd MMM yyyy")</div>
							</div>
							<div class="dz-info">
								<h3 class="dz-title mb-0">
									<a href="@Url.Action("BlogPost","Blog",new{id = blog.Id})">@blog.Title</a>
								</h3>
								<ul class="blog-social">
									<li>
										<a class="share-btn" href="javascript:void(0);">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
												<path d="M7 17L17 7" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
												<path d="M7 7H17V17" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
											</svg>
										</a>								
										<ul class="sub-team-social">
											<li><a href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
											<li><a href="https://twitter.com/" target="_blank"><i class="fab fa-twitter"></i></a></li>
											<li><a href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram"></i></a></li>
											<li><a href="https://www.linkedin.com/" target="_blank"><i class="fa-brands fa-linkedin-in"></i></a></li>
										</ul>
									</li>
								</ul>
							</div>
						</div>
					</div>
					}
					